# Generated by Django 5.0.3 on 2024-03-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='количество')),
            ],
            options={
                'verbose_name': 'продукт в корзине',
                'verbose_name_plural': 'продукты в корзине',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='наименование')),
                ('slug', models.CharField(max_length=32, verbose_name='slug')),
                ('image', models.ImageField(upload_to='cat_images/', verbose_name='изоборажение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('products', models.ManyToManyField(to='main.basketproduct', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='наименование')),
                ('slug', models.CharField(max_length=32, verbose_name='slug')),
                ('big_image', models.ImageField(upload_to='product_images/', verbose_name='большое изоборажение')),
                ('middle_image', models.ImageField(upload_to='product_images/', verbose_name='среднее изоборажение')),
                ('small_image', models.ImageField(upload_to='product_images/', verbose_name='маленькое изоборажение')),
                ('price', models.FloatField(verbose_name='цена')),
                ('category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='продукт'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='наименование')),
                ('slug', models.CharField(max_length=32, verbose_name='slug')),
                ('image', models.ImageField(upload_to='subcat_images/', verbose_name='изоборажение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='подкатегория'),
        ),
    ]
